export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const PURCHASE_BURGER_SUCCESS= 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED= 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START= 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_REDIRECT_AFTER_SUCCESS= 'PURCHASE_BURGER_REDIRECT_AFTER_SUCCESS';

export const FETCH_ORDERS_SUCCESS= 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDERS_FAILED= 'FETCH_ORDER_FAILED';
export const FETCH_ORDERS_START= 'FETCH_ORDER_START';
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAILED= 'AUTH_FAILED';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';
export const SET_AUTH_INITIALIZATION_AFTER_RELOAD='SET_AUTH_INITIALIZATION_AFTER_RELOAD';


